# Generated by Django 4.1.4 on 2022-12-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Govn', '0002_govn_description_govn_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='govn',
            name='new_field',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
